[workspace]
resolver = "2"
members = ["crates/opendb", "crates/opendb-desktop"]
default-members = ["crates/opendb"]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.1.0"

[workspace.dependencies]
opendb = { path = "crates/opendb" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
url = "2"
directories = "6"
tempfile = "3"

gpui = { git = "https://github.com/zed-industries/zed", rev = "e0931d5a9dbf4f781b336fdf448739e74a2ac0b5" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "e0931d5a9dbf4f781b336fdf448739e74a2ac0b5", features = ["font-kit"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "7acfc184382d30864a688fdaa6c9ff719efc53ae" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "7acfc184382d30864a688fdaa6c9ff719efc53ae" }
