mod catalog;
mod client;
mod connection;
mod connection_string;
mod engine;
mod list;
mod name;
mod query;
mod schema_change;
mod staged;
mod store;
mod table;
mod table_page;
mod table_structure;

pub use catalog::SystemCatalogPreference;
// Namespace picker helpers for Session chrome (TablePlus-style schema control).
pub use catalog::{default_namespace, tables_in_namespace};
pub use client::{CatalogError, Client, CloseResult, OpenError, PreferenceError, SessionId};
pub use connection::Connection;
pub use connection_string::{ConnectionString, Engine, ParseError};
pub use list::{AddResult, BundleError, ConnectionList};
pub use name::Name;
pub use query::{ExecuteError, QueryResult, ResultStaging, SqlKind};
pub use schema_change::{ColumnDefinition, SchemaChange, SchemaChangeError};
pub use staged::{ApplyError, RowIdentity, StageError, StagedChange, StagedChangeId};
pub use store::{FileStore, StoreError};
pub use table::{Namespace, NamespaceGroup, Table, TableCatalog, TableName};
pub use table_page::{Cell, ColumnName, Filter, Page, TABLE_PAGE_SIZE, TablePage};
pub use table_structure::{StructureColumn, StructureIndex, TableStructure};
