[package]
name = "opendb-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "opendb"
path = "src/main.rs"

[dependencies]
directories.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
opendb.workspace = true
rfd = "0.15"
