name: test

on:
  push:
  pull_request:

jobs:
  opendb:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test -p opendb --locked
